// Generated by scripts/generate-contracts.py. Do not edit.
import Foundation

public struct Tag: Codable, Sendable {
    public let id: String
    public let name: String
    private enum CodingKeys: String, CodingKey {
        case id, name
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}

public struct Collection: Codable, Sendable {
    public let id: String
    public let name: String
    private enum CodingKeys: String, CodingKey {
        case id, name
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
    }
}

public struct AssetFile: Codable, Sendable {
    public let id: String
    public let role: String
    public let originalFilename: String
    public let objectKey: String
    public let mimeType: String
    public let byteSize: Int64
    public let sha256: String
    public let width: Int64?
    public let height: Int64?
    public let state: String
    public let error: String?
    private enum CodingKeys: String, CodingKey {
        case id, role, originalFilename, objectKey, mimeType, byteSize, sha256, width, height, state, error
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(role, forKey: .role)
        try container.encode(originalFilename, forKey: .originalFilename)
        try container.encode(objectKey, forKey: .objectKey)
        try container.encode(mimeType, forKey: .mimeType)
        try container.encode(byteSize, forKey: .byteSize)
        try container.encode(sha256, forKey: .sha256)
        if let value = width { try container.encode(value, forKey: .width) } else { try container.encodeNil(forKey: .width) }
        if let value = height { try container.encode(value, forKey: .height) } else { try container.encodeNil(forKey: .height) }
        try container.encode(state, forKey: .state)
        if let value = error { try container.encode(value, forKey: .error) } else { try container.encodeNil(forKey: .error) }
    }
}

public struct Asset: Codable, Sendable {
    public let id: String
    public let libraryId: String
    public let kind: String
    public let name: String
    public let note: String
    public let source: String
    public let createdAt: String
    public let updatedAt: String
    public let capturedAt: String?
    public let favorite: Bool
    public let revision: Int64
    public let state: String
    public let trashedAt: String?
    public let archivedAt: String?
    public let tags: [Tag]
    public let collections: [Collection]
    public let files: [AssetFile]
    public let storageLocation: String
    public let originalOwnership: String
    public let remoteAvailable: Bool
    public let localCleanupPending: Bool
    private enum CodingKeys: String, CodingKey {
        case id, libraryId, kind, name, note, source, createdAt, updatedAt, capturedAt, favorite, revision, state, trashedAt, archivedAt, tags, collections, files, storageLocation, originalOwnership, remoteAvailable, localCleanupPending
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(libraryId, forKey: .libraryId)
        try container.encode(kind, forKey: .kind)
        try container.encode(name, forKey: .name)
        try container.encode(note, forKey: .note)
        try container.encode(source, forKey: .source)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(updatedAt, forKey: .updatedAt)
        if let value = capturedAt { try container.encode(value, forKey: .capturedAt) } else { try container.encodeNil(forKey: .capturedAt) }
        try container.encode(favorite, forKey: .favorite)
        try container.encode(revision, forKey: .revision)
        try container.encode(state, forKey: .state)
        if let value = trashedAt { try container.encode(value, forKey: .trashedAt) } else { try container.encodeNil(forKey: .trashedAt) }
        if let value = archivedAt { try container.encode(value, forKey: .archivedAt) } else { try container.encodeNil(forKey: .archivedAt) }
        try container.encode(tags, forKey: .tags)
        try container.encode(collections, forKey: .collections)
        try container.encode(files, forKey: .files)
        try container.encode(storageLocation, forKey: .storageLocation)
        try container.encode(originalOwnership, forKey: .originalOwnership)
        try container.encode(remoteAvailable, forKey: .remoteAvailable)
        try container.encode(localCleanupPending, forKey: .localCleanupPending)
    }
}

public struct AssetPage: Codable, Sendable {
    public let items: [Asset]
    public let total: Int64
    public let nextCursor: String?
    private enum CodingKeys: String, CodingKey {
        case items, total, nextCursor
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(items, forKey: .items)
        try container.encode(total, forKey: .total)
        if let value = nextCursor { try container.encode(value, forKey: .nextCursor) } else { try container.encodeNil(forKey: .nextCursor) }
    }
}

public struct ImportItem: Codable, Sendable {
    public let id: String
    public let filename: String
    public let state: String
    public let assetId: String?
    public let code: String?
    public let message: String
    private enum CodingKeys: String, CodingKey {
        case id, filename, state, assetId, code, message
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(filename, forKey: .filename)
        try container.encode(state, forKey: .state)
        if let value = assetId { try container.encode(value, forKey: .assetId) } else { try container.encodeNil(forKey: .assetId) }
        if let value = code { try container.encode(value, forKey: .code) } else { try container.encodeNil(forKey: .code) }
        try container.encode(message, forKey: .message)
    }
}

public struct ImportJob: Codable, Sendable {
    public let id: String
    public let items: [ImportItem]
    private enum CodingKeys: String, CodingKey {
        case id, items
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(items, forKey: .items)
    }
}

public struct ApiError: Codable, Sendable {
    public let code: String
    public let message: String
    private enum CodingKeys: String, CodingKey {
        case code, message
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encode(message, forKey: .message)
    }
}

public struct AssetSelection: Codable, Sendable {
    public let id: String
    public let revision: Int64
    private enum CodingKeys: String, CodingKey {
        case id, revision
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(revision, forKey: .revision)
    }
}

public struct BulkDownloadRequest: Codable, Sendable {
    public let assets: [AssetSelection]
    private enum CodingKeys: String, CodingKey {
        case assets
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
    }
}

public struct BulkOrganizeRequest: Codable, Sendable {
    public let assets: [AssetSelection]
    public let entity: String
    public let itemIds: [String]
    public let mode: String
    private enum CodingKeys: String, CodingKey {
        case assets, entity, itemIds, mode
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
        try container.encode(entity, forKey: .entity)
        try container.encode(itemIds, forKey: .itemIds)
        try container.encode(mode, forKey: .mode)
    }
}

public struct ArchiveRequest: Codable, Sendable {
    public let revision: Int64
    public let archived: Bool
    private enum CodingKeys: String, CodingKey {
        case revision, archived
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
        try container.encode(archived, forKey: .archived)
    }
}

public struct BulkArchiveRequest: Codable, Sendable {
    public let assets: [AssetSelection]
    public let archived: Bool
    private enum CodingKeys: String, CodingKey {
        case assets, archived
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(assets, forKey: .assets)
        try container.encode(archived, forKey: .archived)
    }
}

public struct CollectionArchiveSummary: Codable, Sendable {
    public let normalCount: Int64
    public let archiveCount: Int64
    public let token: String
    private enum CodingKeys: String, CodingKey {
        case normalCount, archiveCount, token
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(normalCount, forKey: .normalCount)
        try container.encode(archiveCount, forKey: .archiveCount)
        try container.encode(token, forKey: .token)
    }
}

public struct CollectionArchiveRequest: Codable, Sendable {
    public let archived: Bool
    public let token: String
    private enum CodingKeys: String, CodingKey {
        case archived, token
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(archived, forKey: .archived)
        try container.encode(token, forKey: .token)
    }
}

public struct ArchiveResult: Codable, Sendable {
    public let updated: Int64
    private enum CodingKeys: String, CodingKey {
        case updated
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updated, forKey: .updated)
    }
}

public struct BulkOrganizeResult: Codable, Sendable {
    public let updated: Int64
    private enum CodingKeys: String, CodingKey {
        case updated
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(updated, forKey: .updated)
    }
}

public struct TransferRequest: Codable, Sendable {
    public let revision: Int64
    public let destination: String
    public let removeLocal: Bool
    private enum CodingKeys: String, CodingKey {
        case revision, destination, removeLocal
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(revision, forKey: .revision)
        try container.encode(destination, forKey: .destination)
        try container.encode(removeLocal, forKey: .removeLocal)
    }
}

public struct StorageRoot: Codable, Sendable {
    public let id: String
    public let path: String
    public let syncedAt: String?
    public let state: String
    private enum CodingKeys: String, CodingKey {
        case id, path, syncedAt, state
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(path, forKey: .path)
        if let value = syncedAt { try container.encode(value, forKey: .syncedAt) } else { try container.encodeNil(forKey: .syncedAt) }
        try container.encode(state, forKey: .state)
    }
}

public struct SyncDirectoryRequest: Codable, Sendable {
    public let path: String
    public let rootId: String?
    private enum CodingKeys: String, CodingKey {
        case path, rootId
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(path, forKey: .path)
        if let value = rootId { try container.encode(value, forKey: .rootId) } else { try container.encodeNil(forKey: .rootId) }
    }
}

public struct SyncDirectoryResult: Codable, Sendable {
    public let added: Int64
    public let matched: Int64
    public let moved: Int64
    public let changed: Int64
    public let missing: Int64
    public let failed: Int64
    public let rootId: String
    public let limited: Bool
    private enum CodingKeys: String, CodingKey {
        case added, matched, moved, changed, missing, failed, rootId, limited
    }
    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(added, forKey: .added)
        try container.encode(matched, forKey: .matched)
        try container.encode(moved, forKey: .moved)
        try container.encode(changed, forKey: .changed)
        try container.encode(missing, forKey: .missing)
        try container.encode(failed, forKey: .failed)
        try container.encode(rootId, forKey: .rootId)
        try container.encode(limited, forKey: .limited)
    }
}

