"""Generate Web and Swift DTOs from the limited JSON Schema vocabulary in our contract."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SCHEMA = json.loads((ROOT / 'contracts/asset.schema.json').read_text(encoding='utf-8'))


def type_name(prop, swift=False):
    if '$ref' in prop:
        return prop['$ref'].split('/')[-1]
    value = prop['type']
    nullable = isinstance(value, list)
    kind = next(x for x in value if x != 'null') if nullable else value
    types = {'string': 'String', 'integer': 'Int64', 'boolean': 'Bool'} if swift else {'string': 'string', 'integer': 'number', 'boolean': 'boolean'}
    result = f'[{type_name(prop["items"], True)}]' if swift and kind == 'array' else f'{type_name(prop["items"])}[]' if kind == 'array' else types[kind]
    return result + ('?' if swift else ' | null') if nullable else result


def generated():
    ts = ['// Generated by scripts/generate-contracts.py. Do not edit.']
    sw = ['// Generated by scripts/generate-contracts.py. Do not edit.', 'import Foundation', '']
    for name, model in SCHEMA['$defs'].items():
        ts.append(f'export interface {name} {{')
        sw.append(f'public struct {name}: Codable, Sendable {{')
        for key, prop in model['properties'].items():
            ts.append(f'  {key}: {type_name(prop)};')
            sw.append(f'    public let {key}: {type_name(prop, True)}')
        sw.append('    private enum CodingKeys: String, CodingKey {')
        sw.append('        case ' + ', '.join(model['properties']))
        sw.append('    }')
        sw.append('    public func encode(to encoder: Encoder) throws {')
        sw.append('        var container = encoder.container(keyedBy: CodingKeys.self)')
        for key, prop in model['properties'].items():
            if isinstance(prop.get('type'), list):
                sw.append(f'        if let value = {key} {{ try container.encode(value, forKey: .{key}) }} else {{ try container.encodeNil(forKey: .{key}) }}')
            else:
                sw.append(f'        try container.encode({key}, forKey: .{key})')
        sw.append('    }')
        ts.append('}\n')
        sw.append('}\n')
    return {ROOT / 'web/src/generated/contracts.ts': '\n'.join(ts) + '\n', ROOT / 'Sources/AssetLibraryContract/Models.swift': '\n'.join(sw) + '\n', ROOT / 'Tests/AssetLibraryContractTests/asset.json': (ROOT / 'contracts/asset.example.json').read_text(encoding='utf-8')}


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, content in generated().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != content:
                raise SystemExit(f'Contract drift: {path.relative_to(ROOT)}')
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding='utf-8', newline='\n')
    print('PASS: Web/Swift contract generation' + (' check' if args.check else ''))


if __name__ == '__main__':
    main()
